### PR TITLE
ci: Release v2.0.2

### PR DESCRIPTION
**Pull request by pmuens**

### CODE REVIEW

**Comment by yugasun** [comment]
@medikoo Could you help to review this release PR?

**Comment by pmuens** [comment]
@yugasun can you try to approve it? Maybe that's sufficient?

**Comment by yugasun** [comment]
@pmuens  It't required

**Comment by pmuens** [comment]
@yugasun yes, I thought that you can maybe approve it. Not sure if you need to be part of a special team to do a final approval, though.

**Review by medikoo — APPROVED** [review]
Sorry, for delay!

**Comment by pmuens** [comment]
Thanks @medikoo 👍

**Pull request merged**
