### PR TITLE
Update koa component docs

### PR DESCRIPTION
**Pull request by tinafangkunding**
Update koa component docs

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
Thanks @tinafangkunding ! Can you ensure prettier formatting (just run `npm run prettify:updated`) ?

**Comment by tinafangkunding** [comment]
Yes sure!

**Comment by tinafangkunding** [comment]
> Thanks @tinafangkunding ! Can you ensure prettier formatting (just run `npm run prettify:updated`) ?

Hey @medikoo , I think the problem is `Failed at the @serverless/tencent-koa@0.0.0 prettify:updated script.`, I think it is because tencent-koa component is not published to npm.

**Comment by medikoo** [comment]
> I think it is because tencent-koa component is not published to npm.

hmm.. this shouldn't make a difference. With what error it exactly failed? Do you have it properly installed locally?

And concerning publishing it'll be once this PR is merged: https://github.com/serverless-components/tencent-koa/pull/2 (I wait for @eahefnawy approval, but you may approve that as well for that :)

**Review by medikoo — APPROVED** [review]
Thanks @tinafangkunding !

**Pull request merged**
